apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: logwise
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "SECRET_ACCESS_KEY_ID" # Replace with your AWS access key id
  AWS_SECRET_ACCESS_KEY: "SECRET_ACCESS_KEY" # Replace with your AWS secret access key
  AWS_SESSION_TOKEN: "SECRET_SESSION_TOKEN" # Replace with your AWS session token
