apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: logwise
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: YOUR_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY
  AWS_SESSION_TOKEN: YOUR_AWS_SESSION_TOKEN