apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: logwise
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIA54S6SGWZTDNSDOQX"
  AWS_SECRET_ACCESS_KEY: "KrBGYlHMtbIuYkOv3LAoR0Spp4zyyurwtV8qRsot"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEMP//////////wEaCXVzLWVhc3QtMSJGMEQCIAwlUD6Xiq/dRSQZtO/tJ/ZAPOZkwxn638cQASLHL1xjAiBeff5Brs/lIQQXwc4S01aPaFdbYLRDiUCrSTJnJg95UiqYAwiM//////////8BEAQaDDk1NDc1NDgwNzIxOSIMlQJRHXy4ur68NSY4KuwCcEs/T+lGXRfzq7VIbe52Dt2j+M4NnUCRs76sAnbDN9N5vYklZC5poYNf+Yyu10Wl4Mcre/1ob2jiEiqDIfNbhei+MI9/5OdJEuukauS/7VS53ssAGj57Ipz9hUD7vQKez6Z/2qOj+f831nBxm+DD9lr6LAYL22+U7duSrHjA6UMJqWeSutcG8D1Ww3cYCD4yeiQGg3lE/yg69v2GAb3D8tDj+Vy2skJnI2mIXisyPtSOHsOrSjWYsyszyaSexX2wtrwuAEoj8IIL8YyPgAlsgdwhuO+bUv7KboIBM+EP+cZ58mbfsDlcAu27yWt4vRasr+zO5zTKC87cuW6Swvmlpa6XNts1C6xqnHYIRvWg+wfgEcntYOKdb1TuXTuvPm9ck/pA9+wpAj2aFpak1yq0FRLF4ASki+rZNRz2JFD985nPdm6/dDs9b2rdY/0/UIBrFMXaoChULuU7jm9Uz8kak1zTNxNMfMBRW5KCIjDymv7KBjqlAb3EnzqABGyLOZ8b8aYa4Pb3Bso+ywvlf3lBtykCteLIaclG9D5V/+d/tAHDfq9BC7nRXiHDgDE+p8kS1pDA64pmcRxfiywUzTjmsq91sos0fWtevVFoGFBXFnS0Cq5cRJRH3K5UgbSmvyIdsebO7hoiuD9eSdhKe9AyEeXJPt6uBi//L15hjBrB7gnrqpI26bYICe/Rw1ClsoalZLG6Mk+Dqo+2Iw=="
