apiVersion: v1
kind: Secret
metadata:
  name: orch-db-secret
  namespace: {{ include "logwise.namespace" . }}
type: Opaque
stringData:
  username: "{{ .Values.mysql.orchestrator.username }}"
  password: "{{ .Values.mysql.orchestrator.password }}"


