apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ include "logwise.namespace" . }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.aws.accessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.aws.secretAccessKey }}"
  AWS_SESSION_TOKEN: "{{ .Values.aws.sessionToken }}"

