apiVersion: v1
kind: Secret
metadata:
  name: grafana-db-secret
  namespace: {{ include "logwise.namespace" . }}
type: Opaque
stringData:
  username: "{{ .Values.mysql.grafana.username }}"
  password: "{{ .Values.mysql.grafana.password }}"


