apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ include "logwise.namespace" . }}
type: Opaque
stringData:
  accessKeyId: "{{ .Values.aws.accessKeyId }}"
  secretAccessKey: "{{ .Values.aws.secretAccessKey }}"
  sessionToken: "{{ .Values.aws.sessionToken }}"


