# Provision Athena datasource. Requires GF_INSTALL_PLUGINS=grafana-athena-datasource

apiVersion: 1

datasources:
  - name: Athena
    type: grafana-athena-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      region: ${AWS_REGION}
      workgroup: ${ATHENA_WORKGROUP}
      catalog: ${ATHENA_CATALOG}
      database: ${ATHENA_DATABASE}
      outputLocation: ${S3_ATHENA_OUTPUT}
    secureJsonData: {}


